// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToe.Web.Data;

#nullable disable

namespace TicTacToe.Web.Data.Migrations
{
    [DbContext(typeof(TicTacToeDbContext))]
    [Migration("20260430100602_InitialServerMatchState")]
    partial class InitialServerMatchState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TicTacToe.Web.Data.BrowserIdentityEntity", b =>
                {
                    b.Property<string>("BrowserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("BrowserId");

                    b.ToTable("BrowserIdentities");
                });

            modelBuilder.Entity("TicTacToe.Web.Data.MatchSessionEntity", b =>
                {
                    b.Property<string>("BrowserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardState")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinningLineState")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("BrowserId");

                    b.ToTable("MatchSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
