global using Bunit;
global using FluentAssertions;
global using Microsoft.Extensions.DependencyInjection;
global using TicTacToe.Core.Contracts;
global using TicTacToe.Core.Models;
global using TicTacToe.Web.Client.Components;
global using TicTacToe.Web.Client.Pages;
global using TicTacToe.Web.Client.Services;
global using Xunit;